import { describe, expect, it } from 'vitest';
import { MAX_CODE_BYTES, stripCode, validateTestCode } from '../src/runner/validate.js';

const DEMO_URL = 'http://localhost:4100';

/**
 * Shaped like the output of packages/test-generator/src/emit.ts after prettier: header comments
 * (including a dashboard URL on another origin), the single import, the fixture helper, steps
 * with recorded-origin comments, a network wait and the closing expectations.
 */
const GENERATED = `// Generated by Repro. Do not edit by hand; regenerate it from the session instead.
// Session: 6f1d2c3e-4b5a-4c6d-8e7f-9a0b1c2d3e4f
// Project: demo
// Recorded: 2026-09-09T12:00:00.000Z
// Release: 1.4.2
// Browser: Chrome 140
// Incident: TypeError: Cannot read properties of undefined (reading 'toUpperCase')
// Dashboard: http://localhost:3000/projects/demo/sessions/6f1d2c3e-4b5a-4c6d-8e7f-9a0b1c2d3e4f
// Generator: @repro/test-generator 0.1.0
// Source hash: 0123456789abcdef
// Omitted events: 1 (each one is listed with its reason in the Repro dashboard)

import { test, expect } from '@playwright/test';

// Values Repro redacted at capture time are replaced by fixtures. Provide each one through
// the environment variable named in the comment next to its step.
const fixture = (name: string) =>
  process.env[\`REPRO_FIXTURE_\${name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()}\`] ??
  \`REDACTED_\${name}\`;

test('Checkout fails with TypeError', async ({ page }) => {
  const pageErrors: string[] = [];
  page.on('pageerror', (error) => pageErrors.push(String(error)));

  // Step 1 (00:00.000): navigate to /login
  // Recorded origin: http://localhost:4100
  await page.goto('/login');
  await expect(page.getByLabel('Email')).toBeVisible();

  // Step 2 (00:01.200): fill "Email"
  await page.getByLabel('Email').fill('import data from fetch(x)');

  // Step 3 (00:02.000): fill "Password"
  await page.getByLabel('Password').fill(fixture('password')); // value redacted at capture; provide REPRO_FIXTURE_PASSWORD

  // Step 4 (00:03.000): click "Sign in"
  // The recording shows POST /api/login after this step; wait for it below.
  const responsePromise = page.waitForResponse((response) => new URL(response.url()).pathname === '/api/login' && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Sign in' }).click();
  const response = await responsePromise;
  expect(response.ok(), 'POST /api/login should succeed').toBeTruthy();

  // Skipped select an option in "Shipping" (seq 9): No option value was recorded for this select.

  // No submit button was recorded for this form, so it is submitted directly.
  await page.getByTestId('checkout-form').evaluate((form) => (form as HTMLFormElement).requestSubmit());

  // Success state. The recorded session failed here; a fixed build must reach it cleanly.
  await expect(page.getByTestId('order-confirmation')).toBeVisible();
  // Recorded error: TypeError: Cannot read properties of undefined (reading 'toUpperCase') in eval(require("fs"))
  await page.waitForLoadState('networkidle');
  expect(pageErrors, 'the workflow should complete without uncaught errors').toEqual([]);
});
`;

const withLine = (line: string) => GENERATED.replace("await page.goto('/login');", `await page.goto('/login');\n  ${line}`);

describe('stripCode', () => {
  it('blanks line and block comments but keeps string contents, preserving offsets', () => {
    const code = "const a = 'http://x'; // http://comment\n/* block\nhttp://block */ const b = \"y\";";
    const stripped = stripCode(code, { keepStrings: true });
    expect(stripped).toHaveLength(code.length);
    expect(stripped.replace(/ +/g, ' ')).toBe("const a = 'http://x'; \n \n const b = \"y\";");
  });

  it('blanks string contents when asked, keeping the quotes and offsets', () => {
    const code = "fill('import x')\n`tpl ${a}`";
    const stripped = stripCode(code, { keepStrings: false });
    expect(stripped).toHaveLength(code.length);
    expect(stripped.replace(/ +/g, '')).toBe("fill('')\n``");
  });

  it('does not treat // inside a string as a comment', () => {
    expect(stripCode("goto('http://evil.example/a')", { keepStrings: true })).toBe("goto('http://evil.example/a')");
  });
});

describe('validateTestCode', () => {
  it('accepts what the generator emits, including fixtures and dashboard links in comments', () => {
    expect(validateTestCode(GENERATED, DEMO_URL)).toEqual({ ok: true });
  });

  it('accepts a double-quoted import as well', () => {
    const code = GENERATED.replace("from '@playwright/test';", 'from "@playwright/test";');
    expect(validateTestCode(code, DEMO_URL)).toEqual({ ok: true });
  });

  it('rejects code over 64 KB', () => {
    const padded = GENERATED + '\n' + '// x'.repeat(1) + 'x'.repeat(MAX_CODE_BYTES);
    const result = validateTestCode(padded, DEMO_URL);
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.reason).toMatch(/limit is 65536 bytes/);
  });

  it('rejects a second import', () => {
    const code = GENERATED.replace("import { test, expect } from '@playwright/test';", "import { devices } from '@playwright/test';\nimport { test, expect } from '@playwright/test';");
    const result = validateTestCode(code, DEMO_URL);
    expect(result).toMatchObject({ ok: false, reason: expect.stringMatching(/exactly one import/) });
  });

  it('rejects a different single import', () => {
    const code = GENERATED.replace("import { test, expect } from '@playwright/test';", "import { test, expect, chromium } from '@playwright/test';");
    expect(validateTestCode(code, DEMO_URL)).toMatchObject({ ok: false, reason: expect.stringMatching(/Only `import/) });
  });

  it('rejects an import hidden after a semicolon on the same line', () => {
    const code = GENERATED.replace('const pageErrors: string[] = [];', "const pageErrors: string[] = []; import('node:os');");
    expect(validateTestCode(code, DEMO_URL)).toMatchObject({ ok: false });
  });

  it.each([
    ["require('child_process')", /require\(\)/],
    ["await import('node:os')", /dynamic import/],
    ['const cp = child_process', /child_process/],
    ["eval('1')", /eval\(\)/],
    ["new Function('return 1')()", /Function\(\)/],
    ["await fetch('/api/x')", /fetch\(\)/],
    ["const p = process.env.DATABASE_URL", /process\.env\.REPRO_FIXTURE_/],
    ['process.exit(1)', /process\.env\.REPRO_FIXTURE_/],
    ["process['env']", /process\.env\.REPRO_FIXTURE_/],
    ["const m = 'fs'", /fs or net/],
    ["const m = 'node:net'", /fs or net/],
    ["const m = 'fs/promises'", /fs or net/],
  ])('rejects %s', (line, reason) => {
    const result = validateTestCode(withLine(line + ';'), DEMO_URL);
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.reason).toMatch(reason);
  });

  it('allows the bracket and dot forms of a fixture read', () => {
    expect(validateTestCode(withLine("const a = process.env.REPRO_FIXTURE_CARD;"), DEMO_URL)).toEqual({ ok: true });
    expect(validateTestCode(withLine("const b = process.env['REPRO_FIXTURE_CARD'];"), DEMO_URL)).toEqual({ ok: true });
  });

  it('rejects absolute URLs on another origin, even inside strings', () => {
    const result = validateTestCode(withLine("await page.getByRole('link').fill('https://evil.example/collect');"), DEMO_URL);
    expect(result).toMatchObject({ ok: false, reason: expect.stringMatching(/only reference the target application/) });
  });

  it('rejects the demo host on another port', () => {
    const result = validateTestCode(withLine("await page.goto('/x?next=http://localhost:4000/v1/ingest');"), DEMO_URL);
    expect(result).toMatchObject({ ok: false, reason: expect.stringMatching(/localhost:4000/) });
  });

  it('accepts absolute URLs on the demo origin in code', () => {
    expect(validateTestCode(withLine("await expect(page).toHaveURL('http://localhost:4100/checkout');"), DEMO_URL)).toEqual({ ok: true });
  });

  it.each([
    "await page.goto('http://localhost:4100/login');",
    "await page.goto('//localhost:4100/login');",
    'await page.goto(target);',
    'await page.goto(`/${route}`);',
  ])('rejects %s', (line) => {
    const result = validateTestCode(withLine(line), DEMO_URL);
    expect(result).toMatchObject({ ok: false, reason: expect.stringMatching(/page\.goto\(\) must receive a relative path literal/) });
  });

  it('ignores banned words that only appear in comments', () => {
    const code = withLine("// Recorded error: ReferenceError: require is not defined at eval(fetch('https://cdn.example/x'))");
    expect(validateTestCode(code, DEMO_URL)).toEqual({ ok: true });
  });
});
