import { sql } from 'drizzle-orm';
import {
  bigint,
  customType,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType() {
    return 'bytea';
  },
});

const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
};

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  name: text('name').notNull(),
  ...timestamps,
});

export const projects = pgTable(
  'projects',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    slug: text('slug').notNull().unique(),
    name: text('name').notNull(),
    /** Sessions older than this are deleted by the retention job. */
    retentionDays: integer('retention_days').notNull().default(30),
    ...timestamps,
  },
);

export const projectMembers = pgTable(
  'project_members',
  {
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    role: text('role').notNull().default('owner'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('project_members_pk').on(t.projectId, t.userId)],
);

export const ingestionKeys = pgTable(
  'ingestion_keys',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    label: text('label').notNull(),
    /** First characters of the key, shown in the UI. */
    prefix: text('prefix').notNull(),
    /** SHA-256 of the full key. The plaintext key is never stored. */
    keyHash: text('key_hash').notNull().unique(),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('ingestion_keys_prefix_idx').on(t.prefix), index('ingestion_keys_project_idx').on(t.projectId)],
);

export const sessionStatus = pgEnum('session_status', ['recording', 'completed', 'expired']);

export const sessions = pgTable(
  'sessions',
  {
    /** Generated by the SDK. */
    id: uuid('id').primaryKey(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    status: sessionStatus('status').notNull().default('recording'),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
    endedAt: timestamp('ended_at', { withTimezone: true }),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
    release: text('release'),
    environment: text('environment'),
    browserName: text('browser_name'),
    browserVersion: text('browser_version'),
    os: text('os'),
    userAgent: text('user_agent'),
    viewportWidth: integer('viewport_width'),
    viewportHeight: integer('viewport_height'),
    initialUrl: text('initial_url').notNull(),
    initialRoute: text('initial_route').notNull(),
    routes: jsonb('routes').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    errorCount: integer('error_count').notNull().default(0),
    networkFailureCount: integer('network_failure_count').notNull().default(0),
    eventCount: integer('event_count').notNull().default(0),
    chunkCount: integer('chunk_count').notNull().default(0),
    lastSeq: integer('last_seq').notNull().default(-1),
    sdkVersion: text('sdk_version'),
    externalUserId: text('external_user_id'),
    meta: jsonb('meta').$type<Record<string, unknown>>(),
    ...timestamps,
  },
  (t) => [
    index('sessions_project_started_idx').on(t.projectId, t.startedAt.desc()),
    index('sessions_project_status_idx').on(t.projectId, t.status),
    index('sessions_project_release_idx').on(t.projectId, t.release),
    index('sessions_project_route_idx').on(t.projectId, t.initialRoute),
    index('sessions_project_browser_idx').on(t.projectId, t.browserName),
    index('sessions_project_errors_idx').on(t.projectId, t.errorCount),
  ],
);

export const eventChunks = pgTable(
  'event_chunks',
  {
    id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
    sessionId: uuid('session_id').notNull().references(() => sessions.id, { onDelete: 'cascade' }),
    batchSeq: integer('batch_seq').notNull(),
    firstSeq: integer('first_seq').notNull(),
    lastSeq: integer('last_seq').notNull(),
    eventCount: integer('event_count').notNull(),
    /** Always 'gzip' for now. Lets storage move to object storage later without a schema change. */
    encoding: text('encoding').notNull().default('gzip'),
    /** Where the bytes live. 'inline' means the payload column; later 's3://...' style locators. */
    location: text('location').notNull().default('inline'),
    byteSize: integer('byte_size').notNull(),
    payload: bytea('payload'),
    receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('event_chunks_session_batch_idx').on(t.sessionId, t.batchSeq)],
);

export const incidentKind = pgEnum('incident_kind', ['exception', 'unhandledrejection', 'network', 'console']);
export const incidentStatus = pgEnum('incident_status', ['open', 'resolved']);

export const incidents = pgTable(
  'incidents',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    sessionId: uuid('session_id').notNull().references(() => sessions.id, { onDelete: 'cascade' }),
    kind: incidentKind('kind').notNull(),
    title: text('title').notNull(),
    message: text('message').notNull(),
    fingerprint: text('fingerprint').notNull(),
    firstSeq: integer('first_seq').notNull(),
    firstTs: timestamp('first_ts', { withTimezone: true }).notNull(),
    offsetMs: integer('offset_ms').notNull(),
    route: text('route'),
    release: text('release'),
    status: incidentStatus('status').notNull().default('open'),
    ...timestamps,
  },
  (t) => [
    index('incidents_project_created_idx').on(t.projectId, t.createdAt.desc()),
    index('incidents_project_fingerprint_idx').on(t.projectId, t.fingerprint),
    uniqueIndex('incidents_session_fingerprint_idx').on(t.sessionId, t.fingerprint),
  ],
);

export const generatedTests = pgTable(
  'generated_tests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    sessionId: uuid('session_id').notNull().references(() => sessions.id, { onDelete: 'cascade' }),
    incidentId: uuid('incident_id').references(() => incidents.id, { onDelete: 'set null' }),
    version: integer('version').notNull().default(1),
    name: text('name').notNull(),
    code: text('code').notNull(),
    language: text('language').notNull().default('typescript'),
    framework: text('framework').notNull().default('playwright'),
    /** Hash of the normalised input. Same hash means same generated code. */
    sourceHash: text('source_hash').notNull(),
    generatorVersion: text('generator_version').notNull(),
    selectors: jsonb('selectors').$type<unknown[]>().notNull().default(sql`'[]'::jsonb`),
    omitted: jsonb('omitted').$type<unknown[]>().notNull().default(sql`'[]'::jsonb`),
    warnings: jsonb('warnings').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    expectations: jsonb('expectations').$type<unknown[]>().notNull().default(sql`'[]'::jsonb`),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('generated_tests_session_idx').on(t.sessionId, t.version.desc()), index('generated_tests_project_idx').on(t.projectId, t.createdAt.desc())],
);

export const runStatus = pgEnum('run_status', ['queued', 'running', 'passed', 'failed', 'error', 'timeout']);

export const reproductionRuns = pgTable(
  'reproduction_runs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    sessionId: uuid('session_id').notNull().references(() => sessions.id, { onDelete: 'cascade' }),
    generatedTestId: uuid('generated_test_id').notNull().references(() => generatedTests.id, { onDelete: 'cascade' }),
    status: runStatus('status').notNull().default('queued'),
    target: text('target').notNull().default('demo'),
    targetMode: text('target_mode').notNull().default('broken'),
    queuedAt: timestamp('queued_at', { withTimezone: true }).notNull().defaultNow(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
    durationMs: integer('duration_ms'),
    failureMessage: text('failure_message'),
    logs: text('logs'),
    exitCode: integer('exit_code'),
    artifacts: jsonb('artifacts').$type<{ name: string; contentType: string; bytes: number; path: string }[]>().notNull().default(sql`'[]'::jsonb`),
  },
  (t) => [index('runs_test_idx').on(t.generatedTestId, t.queuedAt.desc()), index('runs_project_idx').on(t.projectId, t.queuedAt.desc())],
);

export const findingKind = pgEnum('finding_kind', ['evidence', 'investigation']);

export const diagnosticFindings = pgTable(
  'diagnostic_findings',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    sessionId: uuid('session_id').notNull().references(() => sessions.id, { onDelete: 'cascade' }),
    incidentId: uuid('incident_id').references(() => incidents.id, { onDelete: 'set null' }),
    kind: findingKind('kind').notNull(),
    provider: text('provider').notNull(),
    model: text('model'),
    evidence: jsonb('evidence').$type<unknown>(),
    investigation: jsonb('investigation').$type<unknown>(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('findings_session_idx').on(t.sessionId, t.createdAt.desc())],
);

export const jobStatus = pgEnum('job_status', ['queued', 'running', 'done', 'failed']);

export const jobs = pgTable(
  'jobs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    kind: text('kind').notNull(),
    payload: jsonb('payload').$type<Record<string, unknown>>().notNull(),
    status: jobStatus('status').notNull().default('queued'),
    attempts: integer('attempts').notNull().default(0),
    maxAttempts: integer('max_attempts').notNull().default(3),
    runAfter: timestamp('run_after', { withTimezone: true }).notNull().defaultNow(),
    lockedAt: timestamp('locked_at', { withTimezone: true }),
    lockedBy: text('locked_by'),
    lastError: text('last_error'),
    /** Optional idempotency key so the same work is not queued twice. */
    dedupeKey: text('dedupe_key'),
    ...timestamps,
  },
  (t) => [index('jobs_status_run_after_idx').on(t.status, t.runAfter), uniqueIndex('jobs_dedupe_idx').on(t.dedupeKey)],
);

export const rateLimitBuckets = pgTable('rate_limit_buckets', {
  key: text('key').primaryKey(),
  tokens: integer('tokens').notNull(),
  refilledAt: timestamp('refilled_at', { withTimezone: true }).notNull().defaultNow(),
});

export type SessionRow = typeof sessions.$inferSelect;
export type ProjectRow = typeof projects.$inferSelect;
export type IncidentRow = typeof incidents.$inferSelect;
export type GeneratedTestRow = typeof generatedTests.$inferSelect;
export type RunRow = typeof reproductionRuns.$inferSelect;
export type FindingRow = typeof diagnosticFindings.$inferSelect;
export type JobRow = typeof jobs.$inferSelect;
export type IngestionKeyRow = typeof ingestionKeys.$inferSelect;
export type EventChunkRow = typeof eventChunks.$inferSelect;
